// Extracted blog post data for better organization

export const blogPostsData = [
  {
    id: 1,
    title: "Optimizando tu LLC en EE.UU.: Claves para No Residentes",
    excerpt: "Descubre cómo maximizar los beneficios fiscales y operativos de tu LLC en Estados Unidos siendo extranjero. Evita errores comunes y estructura correctamente.",
    author: "Carlos García",
    date: "2025-04-15",
    tags: ["llc", "fiscalidad", "internacional", "usa"],
    imageSrc: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1632&q=80",
  },
  {
    id: 2,
    title: "El Régimen NHR en Portugal: ¿Sigue Siendo Atractivo para Nómadas Digitales?",
    excerpt: "Analizamos los cambios recientes en el régimen de Residentes No Habituales (NHR) de Portugal y su impacto en freelancers y trabajadores remotos.",
    author: "Sofia Almeida",
    date: "2025-04-10",
    tags: ["nomada", "fiscalidad", "portugal", "internacional"],
    imageSrc: "https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1472&q=80",
  },
  {
    id: 3,
    title: "Pillar Two (BEPS 2.0): Implicaciones para Multinacionales",
    excerpt: "La implementación del impuesto mínimo global del 15% ya está aquí. ¿Cómo afecta a tu grupo empresarial? Claves para el cumplimiento.",
    author: "Dr. Klaus Richter",
    date: "2025-04-05",
    tags: ["fiscalidad", "internacional", "beps", "pillar two", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 4,
    title: "Autónomo vs. S.L. en España: ¿Cuándo Conviene Dar el Salto?",
    excerpt: "Facturación, responsabilidad, costes... Analizamos los pros y contras de ser autónomo frente a constituir una Sociedad Limitada en España.",
    author: "Lucía Fernández",
    date: "2025-03-28",
    tags: ["autonomo", "slsa", "fiscalidad", "espana", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1586473219010-2ffc57b0d282?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1476&q=80",
  },
  {
    id: 5,
    title: "DAC7: Nuevas Obligaciones de Información para Plataformas Digitales",
    excerpt: "Si operas un marketplace o plataforma online en la UE, la directiva DAC7 te afecta. Conoce tus nuevas responsabilidades de reporte fiscal.",
    author: "Equipo Legal ConsultGlobalLex",
    date: "2025-03-20",
    tags: ["fiscalidad", "internacional", "ue", "dac7", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 6,
    title: "Retenciones en Origen (Withholding Tax): Clave en Pagos Internacionales",
    excerpt: "Entender y aplicar correctamente las retenciones en origen es vital para evitar doble imposición. Exploramos convenios y estrategias.",
    author: "Javier Morales",
    date: "2025-03-12",
    tags: ["fiscalidad", "internacional", "withholding tax", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1639754570711-e4e4c6c8d8a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 7,
    title: "Planificación Fiscal para Nómadas Digitales en Latinoamérica",
    excerpt: "Visados, residencia fiscal, impuestos... Navegamos el complejo panorama fiscal para nómadas digitales en países como México, Colombia y Argentina.",
    author: "Isabella Rossi",
    date: "2025-03-01",
    tags: ["nomada", "fiscalidad", "internacional", "latam"],
    imageSrc: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 8,
    title: "IRPF 2024 en España: Novedades y Deducciones Clave",
    excerpt: "Un resumen de los cambios más importantes en el Impuesto sobre la Renta de las Personas Físicas para este año y cómo optimizar tu declaración.",
    author: "Equipo Fiscal ConsultGlobalLex",
    date: "2025-02-25",
    tags: ["irpf", "fiscalidad", "espana"],
    imageSrc: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1311&q=80",
  },
  {
    id: 9,
    title: "IVA Intracomunitario: Guía Esencial para Empresas",
    excerpt: "El ROI/VIES, facturación, declaraciones... Todo lo que necesitas saber para gestionar correctamente el IVA en operaciones B2B dentro de la UE.",
    author: "Martina López",
    date: "2025-02-18",
    tags: ["ivaigic", "fiscalidad", "internacional", "ue", "espana"],
    imageSrc: "https://images.unsplash.com/photo-1586473219010-2ffc57b0d282?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1476&q=80",
  },
  {
    id: 10,
    title: "Precios de Transferencia: Cumplimiento y Documentación",
    excerpt: "Evita sanciones y asegura el cumplimiento con las normativas de precios de transferencia. Principios clave y obligaciones documentales.",
    author: "David Chen",
    date: "2025-02-10",
    tags: ["fiscalidad", "internacional", "transfer pricing", "legal", "beps"],
    imageSrc: "https://images.unsplash.com/photo-1554224154-26032f7a9139?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 11,
    title: "Constitución de Holdings: Ventajas y Estructuras Comunes",
    excerpt: "Una sociedad holding puede ser clave para la protección patrimonial y la optimización fiscal. Analizamos cuándo y cómo crear una.",
    author: "Equipo Legal ConsultGlobalLex",
    date: "2025-01-29",
    tags: ["legal", "fiscalidad", "internacional", "slsa"],
    imageSrc: "https://images.unsplash.com/photo-1600880292203-757bb62b4be3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 12,
    title: "¿Residencia Fiscal en Andorra? Mitos y Realidades",
    excerpt: "Andorra sigue siendo atractiva fiscalmente, pero los requisitos son estrictos. Desmontamos mitos comunes y explicamos el proceso real.",
    author: "Marc Vidal",
    date: "2025-01-22",
    tags: ["fiscalidad", "internacional", "andorra", "nomada"],
    imageSrc: "https://images.unsplash.com/photo-1591491519860-5317a5184fed?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 13,
    title: "Fiscalidad de Criptomonedas en España: Guía 2025",
    excerpt: "Declaración de ganancias, modelos 721 y 172/173... Aclaramos las obligaciones fiscales sobre criptoactivos en España.",
    author: "Elena Ríos",
    date: "2025-01-15",
    tags: ["cripto", "fiscalidad", "irpf", "espana"],
    imageSrc: "https://images.unsplash.com/photo-1639322537228-f710d846310a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1632&q=80",
  },
  {
    id: 14,
    title: "Tratados de Doble Imposición: ¿Cómo Funcionan?",
    excerpt: "Son herramientas clave para evitar pagar impuestos dos veces por el mismo ingreso. Explicamos su funcionamiento y cómo aplicarlos.",
    author: "Javier Morales",
    date: "2025-01-08",
    tags: ["fiscalidad", "internacional", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1665686308827-eb62e4f6604d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
   {
    id: 15,
    title: "Fiscalidad Cripto en Portugal: El Fin del Paraíso",
    excerpt: "Portugal ha introducido impuestos sobre las criptomonedas. Analizamos cómo afecta a inversores y traders residentes y no residentes.",
    author: "Sofia Almeida",
    date: "2025-04-20",
    tags: ["cripto", "fiscalidad", "portugal", "internacional"],
    imageSrc: "https://images.unsplash.com/photo-1640955014218-3533a130c599?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 16,
    title: "Creación de S.L. en España: Pasos y Costes Detallados",
    excerpt: "Guía completa desde la obtención del NIF hasta la inscripción en el Registro Mercantil. Detallamos los trámites, plazos y gastos asociados.",
    author: "Lucía Fernández",
    date: "2025-04-18",
    tags: ["slsa", "legal", "espana"],
    imageSrc: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 17,
    title: "Principales Deducciones IRPF para Autónomos en España",
    excerpt: "Maximiza tu ahorro fiscal conociendo las deducciones más relevantes: gastos de oficina en casa, vehículo, suministros, dietas, etc.",
    author: "Equipo Fiscal ConsultGlobalLex",
    date: "2025-04-12",
    tags: ["autonomo", "irpf", "fiscalidad", "espana"],
    imageSrc: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 18,
    title: "Tratado México-España: Oportunidades Fiscales y de Inversión",
    excerpt: "Analizamos las ventajas del convenio de doble imposición entre México y España para empresas y particulares con intereses en ambos países.",
    author: "Isabella Rossi",
    date: "2025-04-08",
    tags: ["fiscalidad", "internacional", "mexico", "espana", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1560439514-4e9645039924?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80",
  },
  {
    id: 19,
    title: "Facturación Electrónica Obligatoria en España: ¿Estás Preparado?",
    excerpt: "La Ley Crea y Crece impone la factura electrónica. Te explicamos los plazos, requisitos técnicos y cómo adaptarte sin problemas.",
    author: "Martina López",
    date: "2025-04-02",
    tags: ["legal", "fiscalidad", "espana", "autonomo", "slsa"],
    imageSrc: "https://images.unsplash.com/photo-1599488838682-356b317f9b1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 20,
    title: "LLC vs. S-Corp vs. C-Corp en USA: ¿Cuál Elegir?",
    excerpt: "Comparativa detallada de las estructuras empresariales más comunes en EE.UU. para no residentes: impuestos, responsabilidad y flexibilidad.",
    author: "Carlos García",
    date: "2025-03-25",
    tags: ["llc", "slsa", "fiscalidad", "internacional", "usa", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 21,
    title: "Régimen de Módulos (Estimación Objetiva) en España: ¿Sigue Vigente?",
    excerpt: "Analizamos los límites, actividades permitidas y la conveniencia de tributar por módulos frente a estimación directa para autónomos.",
    author: "Equipo Fiscal ConsultGlobalLex",
    date: "2025-03-18",
    tags: ["autonomo", "fiscalidad", "irpf", "ivaigic", "espana"],
    imageSrc: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 22,
    title: "Expatriados en Alemania: Claves Fiscales y Legales",
    excerpt: "Guía esencial para trabajadores desplazados a Alemania: Anmeldung, Steuer-ID, seguros, impuestos sobre la renta y convenios.",
    author: "Dr. Klaus Richter",
    date: "2025-03-10",
    tags: ["nomada", "fiscalidad", "internacional", "alemania", "legal"],
    imageSrc: "https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1469&q=80",
  },
  {
    id: 23,
    title: "Smart Contracts: Implicaciones Legales y Fiscales",
    excerpt: "Más allá de la tecnología blockchain, exploramos la validez legal, la tributación y los desafíos regulatorios de los contratos inteligentes.",
    author: "Equipo Legal ConsultGlobalLex",
    date: "2025-03-04",
    tags: ["legal", "fiscalidad", "internacional", "cripto"],
    imageSrc: "https://images.unsplash.com/photo-1605792657660-596af9009e82?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1402&q=80",
  },
  {
    id: 24,
    title: "El IGIC en Canarias: Régimen Especial y Diferencias con IVA",
    excerpt: "El Impuesto General Indirecto Canario (IGIC) tiene particularidades importantes. Comparamos tipos, exenciones y obligaciones con el IVA peninsular.",
    author: "Lucía Fernández",
    date: "2025-02-27",
    tags: ["ivaigic", "fiscalidad", "espana", "canarias"],
    imageSrc: "https://images.unsplash.com/photo-1583211646828-e689ffa0b8ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
   {
    id: 25,
    title: "Fiscalidad para Nómadas Digitales en Italia: Residencia y Régimen 'Impatriati'",
    excerpt: "Analizamos el atractivo régimen fiscal italiano para nuevos residentes y trabajadores cualificados, comparándolo con otras opciones europeas.",
    author: "Isabella Rossi",
    date: "2025-04-25",
    tags: ["nomada", "fiscalidad", "italia", "internacional"],
    imageSrc: "https://images.unsplash.com/photo-1515859896422-170e6a1029d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1395&q=80",
  },
  {
    id: 26,
    title: "Ley Beckham en España: Ventajas y Requisitos Actualizados",
    excerpt: "El régimen especial para impatriados en España sigue siendo muy beneficioso. Explicamos quién puede acogerse y cómo hacerlo correctamente.",
    author: "Equipo Fiscal ConsultGlobalLex",
    date: "2025-04-22",
    tags: ["nomada", "fiscalidad", "espana", "irpf", "internacional"],
    imageSrc: "https://images.unsplash.com/photo-1556156179-401af0cd518f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 27,
    title: "Due Diligence Fiscal en Adquisiciones Internacionales",
    excerpt: "Comprar una empresa en otro país implica riesgos fiscales ocultos. La Due Diligence es esencial para identificar contingencias y valorar correctamente.",
    author: "David Chen",
    date: "2025-04-16",
    tags: ["legal", "fiscalidad", "internacional"],
    imageSrc: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
];